<?php
/**
 * ArrayOfObjectsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mobieve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mobieve Notification
 *
 * Notification API for Mobieve Services
 *
 * OpenAPI spec version: 2019-12-05T21:13:11Z
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mobieve;

/**
 * ArrayOfObjectsTest Class Doc Comment
 *
 * @category    Class
 * @description ArrayOfObjects
 * @package     Mobieve
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ArrayOfObjectsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArrayOfObjects"
     */
    public function testArrayOfObjects()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "current_page"
     */
    public function testPropertyCurrentPage()
    {
    }

    /**
     * Test attribute "first_page_url"
     */
    public function testPropertyFirstPageUrl()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }

    /**
     * Test attribute "last_page"
     */
    public function testPropertyLastPage()
    {
    }

    /**
     * Test attribute "last_page_url"
     */
    public function testPropertyLastPageUrl()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "per_page"
     */
    public function testPropertyPerPage()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }
}
