<?php
/**
 * TemplateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mobieve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mobieve Notification
 *
 * Notification API for Mobieve Services
 *
 * OpenAPI spec version: 2019-12-05T21:13:11Z
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mobieve;

/**
 * TemplateTest Class Doc Comment
 *
 * @category    Class
 * @description Template
 * @package     Mobieve
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TemplateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Template"
     */
    public function testTemplate()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "view_name"
     */
    public function testPropertyViewName()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "channel_id"
     */
    public function testPropertyChannelId()
    {
    }

    /**
     * Test attribute "fields"
     */
    public function testPropertyFields()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
