<?php
/**
 * NotificationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mobieve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mobieve Notification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2019-12-05T14:54:17Z
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mobieve;

use \Mobieve\Configuration;
use \Mobieve\ApiException;
use \Mobieve\ObjectSerializer;

/**
 * NotificationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mobieve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NotificationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for channelsGet
     *
     * .
     *
     */
    public function testChannelsGet()
    {
    }

    /**
     * Test case for messagesGet
     *
     * .
     *
     */
    public function testMessagesGet()
    {
    }

    /**
     * Test case for messagesIdGet
     *
     * .
     *
     */
    public function testMessagesIdGet()
    {
    }

    /**
     * Test case for messagesPost
     *
     * .
     *
     */
    public function testMessagesPost()
    {
    }

    /**
     * Test case for templatesGet
     *
     * .
     *
     */
    public function testTemplatesGet()
    {
    }

    /**
     * Test case for templatesIdPost
     *
     * .
     *
     */
    public function testTemplatesIdPost()
    {
    }

    /**
     * Test case for templatesPost
     *
     * .
     *
     */
    public function testTemplatesPost()
    {
    }
}
