<?php
/**
 * NotificationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mobieve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mobieve Notification
 *
 * Notification API for Mobieve Services
 *
 * OpenAPI spec version: 2019-12-05T21:13:11Z
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mobieve;

use \Mobieve\Configuration;
use \Mobieve\ApiException;
use \Mobieve\ObjectSerializer;

/**
 * NotificationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mobieve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NotificationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMessage
     *
     * .
     *
     */
    public function testCreateMessage()
    {
    }

    /**
     * Test case for createTemplate
     *
     * .
     *
     */
    public function testCreateTemplate()
    {
    }

    /**
     * Test case for getChannels
     *
     * .
     *
     */
    public function testGetChannels()
    {
    }

    /**
     * Test case for getMessage
     *
     * .
     *
     */
    public function testGetMessage()
    {
    }

    /**
     * Test case for getMessages
     *
     * .
     *
     */
    public function testGetMessages()
    {
    }

    /**
     * Test case for getTemplates
     *
     * .
     *
     */
    public function testGetTemplates()
    {
    }

    /**
     * Test case for updateTemplate
     *
     * .
     *
     */
    public function testUpdateTemplate()
    {
    }
}
